import { PERMISSIONS } from "@/config/permissions";
import type { ApplicationRow, AuditLogRow, AuthUser, IntegrationStatus, StaffRow, TicketRow } from "@/types/domain";

export const demoUser: AuthUser = {
  id: "demo-owner",
  telegramId: "123456789",
  telegramUsername: "owner",
  displayName: "Owner MAJURE",
  isDemo: true,
  roles: [
    {
      id: "role-owner",
      key: "owner",
      name: "Owner",
      kind: "OWNER",
      permissions: [...PERMISSIONS],
    },
  ],
  permissions: [...PERMISSIONS],
};

export const staffRows: StaffRow[] = [
  {
    id: "staff-1",
    username: "MajureOwner",
    uuid: "00000000-0000-0000-0000-000000000001",
    telegramId: "123456789",
    discordUsername: "owner#0001",
    currentLuckPermsGroup: "owner",
    projectPosition: "Владелец проекта",
    assignedAt: "2026-07-01T10:00:00.000Z",
    assignedBy: "System",
    status: "ACTIVE",
    notes: "Полный доступ к панели и интеграциям.",
  },
  {
    id: "staff-2",
    username: "AstraMajure",
    uuid: "00000000-0000-0000-0000-000000000002",
    telegramId: "200000001",
    discordUsername: "astra.majure",
    currentLuckPermsGroup: "curator",
    projectPosition: "Куратор модерации",
    assignedAt: "2026-07-04T11:30:00.000Z",
    assignedBy: "MajureOwner",
    status: "ACTIVE",
  },
  {
    id: "staff-3",
    username: "NordKeeper",
    uuid: "00000000-0000-0000-0000-000000000003",
    telegramId: "200000002",
    discordUsername: "nordkeeper",
    currentLuckPermsGroup: "moderator",
    pendingLuckPermsGroup: "admin",
    projectPosition: "Модератор",
    assignedAt: "2026-07-06T15:05:00.000Z",
    assignedBy: "AstraMajure",
    status: "PROBATION",
  },
  {
    id: "staff-4",
    username: "VelvetLaw",
    uuid: "00000000-0000-0000-0000-000000000004",
    telegramId: "200000003",
    discordUsername: "velvetlaw",
    currentLuckPermsGroup: "support",
    projectPosition: "Техподдержка",
    assignedAt: "2026-07-07T09:45:00.000Z",
    assignedBy: "MajureOwner",
    status: "VACATION",
  },
];

export const applicationRows: ApplicationRow[] = [
  {
    id: "app-1",
    googleSheetRowId: "row-101",
    submittedAt: "2026-07-08T18:25:00.000Z",
    candidateUsername: "QuartzVote",
    telegramUsername: "@quartzvote",
    discordUsername: "quartzvote",
    status: "NEW",
    answers: {
      "Возраст": "18",
      "Часовой пояс": "МСК",
      "Опыт": "Модерировал RP-сервер 8 месяцев",
      "Почему MAJURE": "Хочу помогать с политическими конфликтами и правилами войн.",
    },
    comments: [],
  },
  {
    id: "app-2",
    googleSheetRowId: "row-102",
    submittedAt: "2026-07-08T20:40:00.000Z",
    candidateUsername: "VelvetLaw",
    telegramUsername: "@velvetlaw",
    discordUsername: "velvetlaw",
    status: "IN_PROGRESS",
    assignedReviewer: "AstraMajure",
    answers: {
      "Возраст": "20",
      "Часовой пояс": "МСК+1",
      "Опыт": "Судья на политическом сервере",
      "Почему MAJURE": "Интересна система законов, апелляций и дипломатических конфликтов.",
    },
    comments: [{ id: "comment-1", author: "AstraMajure", body: "Нужен созвон по конфликтам между государствами.", createdAt: "2026-07-09T09:05:00.000Z" }],
  },
  {
    id: "app-3",
    googleSheetRowId: "row-103",
    submittedAt: "2026-07-09T07:50:00.000Z",
    candidateUsername: "CivicMiner",
    telegramUsername: "@civicminer",
    discordUsername: "civicminer",
    status: "REVIEW",
    assignedReviewer: "MajureOwner",
    answers: {
      "Возраст": "17",
      "Часовой пояс": "МСК",
      "Опыт": "Играл на MAJURE со второго сезона",
      "Почему MAJURE": "Хочу развивать правила экономики и помогать новичкам.",
    },
    comments: [{ id: "comment-2", author: "MajureOwner", body: "Проверить историю наказаний.", createdAt: "2026-07-09T10:20:00.000Z" }],
  },
];

export const ticketRows: TicketRow[] = [
  {
    id: "ticket-1",
    source: "TELEGRAM",
    externalThreadId: "tg-5001",
    playerUsername: "CivicMiner",
    externalUsername: "@civicminer",
    title: "Не выдали роль после вступления",
    status: "IN_PROGRESS",
    priority: "HIGH",
    assignedUser: "MajureOwner",
    tags: ["luckperms", "роль"],
    createdAt: "2026-07-09T08:15:00.000Z",
    messages: [
      {
        id: "msg-1",
        authorType: "PLAYER",
        authorName: "CivicMiner",
        body: "Здравствуйте, прошел регистрацию, но роль гражданина не выдалась.",
        visibility: "PUBLIC",
        createdAt: "2026-07-09T08:15:00.000Z",
      },
      {
        id: "msg-2",
        authorType: "ADMIN",
        authorName: "MajureOwner",
        body: "Проверяем синхронизацию с LuckPerms.",
        visibility: "PUBLIC",
        createdAt: "2026-07-09T08:19:00.000Z",
      },
    ],
  },
  {
    id: "ticket-2",
    source: "DISCORD",
    externalThreadId: "dc-7812",
    playerUsername: "RiverDuke",
    externalUsername: "riverduke",
    title: "Апелляция на наказание",
    status: "OPEN",
    priority: "NORMAL",
    assignedUser: "AstraMajure",
    tags: ["апелляция"],
    createdAt: "2026-07-09T09:45:00.000Z",
    messages: [
      {
        id: "msg-3",
        authorType: "PLAYER",
        authorName: "RiverDuke",
        body: "Можно пересмотреть мут? Я приложил скриншот контекста.",
        visibility: "PUBLIC",
        createdAt: "2026-07-09T09:45:00.000Z",
      },
    ],
  },
  {
    id: "ticket-3",
    source: "TELEGRAM",
    externalThreadId: "tg-5008",
    playerUsername: "NorthUnion",
    externalUsername: "@northunion",
    title: "Заявка на ивент между государствами",
    status: "WAITING_PLAYER",
    priority: "LOW",
    assignedUser: "VelvetLaw",
    tags: ["ивенты", "политика"],
    createdAt: "2026-07-08T19:10:00.000Z",
    messages: [
      {
        id: "msg-4",
        authorType: "PLAYER",
        authorName: "NorthUnion",
        body: "Хотим провести саммит с тремя государствами, нужна помощь администрации.",
        visibility: "PUBLIC",
        createdAt: "2026-07-08T19:10:00.000Z",
      },
      {
        id: "msg-5",
        authorType: "ADMIN",
        authorName: "VelvetLaw",
        body: "Пришлите список участников и желаемое время.",
        visibility: "PUBLIC",
        createdAt: "2026-07-08T19:35:00.000Z",
      },
    ],
  },
];

export const auditRows: AuditLogRow[] = [
  { id: "audit-1", actor: "MajureOwner", action: "staff.change_group.queued", entityType: "StaffMember", entityId: "staff-3", createdAt: "2026-07-09T10:30:00.000Z", metadata: { group: "admin" } },
  { id: "audit-2", actor: "AstraMajure", action: "application.status_changed", entityType: "Application", entityId: "app-2", createdAt: "2026-07-09T09:05:00.000Z", metadata: { to: "IN_PROGRESS" } },
  { id: "audit-3", actor: "MajureOwner", action: "ticket.reply.sent", entityType: "Ticket", entityId: "ticket-1", createdAt: "2026-07-09T08:19:00.000Z", metadata: { source: "TELEGRAM" } },
  { id: "audit-4", actor: "System", action: "google_forms.sync.mock", entityType: "IntegrationSyncLog", createdAt: "2026-07-09T07:00:00.000Z", metadata: { imported: 3 } },
];

export const integrationStatuses: IntegrationStatus[] = [
  {
    id: "minecraft",
    name: "Minecraft Plugin API",
    description: "Очередь команд для LuckPerms и синхронизации состава.",
    status: "mock",
    lastSync: "2026-07-09T10:35:00.000Z",
    contract: "POST /api/integrations/minecraft/pull-commands",
  },
  {
    id: "google",
    name: "Google Forms / Sheets",
    description: "Импорт заявок на модератора из таблицы ответов.",
    status: "mock",
    lastSync: "2026-07-09T07:00:00.000Z",
    contract: "POST /api/integrations/google-forms/sync",
  },
  {
    id: "telegram",
    name: "Telegram Bot API",
    description: "Вход администраторов и прием тикетов игроков.",
    status: "mock",
    lastSync: "2026-07-09T10:20:00.000Z",
    contract: "POST /api/integrations/telegram/webhook",
  },
  {
    id: "discord",
    name: "Discord Webhook API",
    description: "Прием обращений и отправка публичных ответов.",
    status: "mock",
    lastSync: "2026-07-09T09:45:00.000Z",
    contract: "POST /api/integrations/discord/webhook",
  },
];
